name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: cd HW3 && npm install

      - name: Run Cypress tests with Mochawesome reporter
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: cd HW3 && npm run report -- --record --key $CYPRESS_RECORD_KEY

      - name: Upload Mochawesome Report
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-report
          path: HW3/mochawesome-report/*.html
